#!/usr/bin/env python3
"""Create paired VH/VL FASTA files for CDR homology analysis."""

import os

# H variants
H_VARIANTS = {
    "V0": "EVQLVQSGAEVKKPGESLKISCKGSGYSFTNYWLGWVRQMPGKGLEWMGDIFPGSGNIHYNEKFKGQVTISADKSISTAYLQWSSLKASDTAMYYCARLRNWDEPMDYWGQGTTVTVSS",
    "V1": "EVQLLQSGAEVKKPGESLKISCKGSGYSFTNYWLGWVKQMPGKGLEWIGDIFPGSGNIHYNEKFKGQATLSADKSISTAYLQWSSLKASDTAMYYCARLRNWDEPMDYWGQGTTVTVSS",
    "V2a": "EVQLLEQSGAEVKKPGESLKISCKGSGYSFTNYWLGWVKQMPGKGLEWIGDIFPGSGNIHYNEKFKGQATLSADKSISTAYLQWSSLKASDTAMYFCARLRNWDEPMDYWGQGTTVTVSS",
    "V2b": "EVQLLEQSGAEVKKPGESLKISCKASGYAFTNYWLGWVKQMPGKGLEWIGDIFPGSGNIHYNEKFKGQATLSADKSISTAYLQWSSLKASDTAMYFCARLRNWDEPMDYWGQGTTVTVSS",
    "V2": "EVQLLEQSGAEVKKPGESVKISCKASGYAFTNYWLGWVKQMPGKGLEWIGDIFPGSGNIHYNEKFKGKATLSADKSISTAYMQLSSLKASDTAMYFCARLRNWDEPMDYWGQGTTVTVSS",
    "V3": "EVQLLEQSGAELKRPGTSVKISCKASGYAFTNYWLGWVKQRPGHGLEWIGDIFPGSGNIHYNEKFKGKATLTADKSSSTAYMQLSSLKASDTAMYFCARLRNWDEPMDYWGQGTTVTVSS",
    "Vmin": "EVQLLEQSGAEVKKPGESLKISCKGSGYAFTNYWLGWVKQMPGKGLEWIGDIFPGSGNIHYNEKFKGKATLTADKSISTAYLQWSSLKASDTAMYFCARLRNWDEPMDYWGQGTTVTVSS",
}

# L variants
L_VARIANTS = {
    "V0": "DIVMTQSPDSLAVSLGERATINCKSSQSLLNSGNQKNYLTWYQQKPGQPPKLLIYWASTRESGVPDRFSGSGSGTDFTLTISSLQAEDVAVYYCQNDYSYPLTFGQGTKLEIK",
    "V1": "DLVMTQSPDSLAVSLGERATINCKSSQSLLNSGNQKNYLTWYQQKPGQPPKLLIYWASTRESGVPDRFSGSGSGTDFTLTISSLQAEDVAVYYCQNDYSYPLTFGQGTKLEIK",
    "V2a": "DLVMTQSPDSLAVSLGERATINCKSSQSLLNSGNQKNYLTWYQQKPGQPPKLLIYWASTRESGVPDRFSGSGSGTDFTLTISSLQAEDVAVYYCQNDYSYPLTFGQGTKLEIK",
    "V2b": "ELVMTQSPDSLAVSLGERATINCKSSQSLLNSGNQKNYLTWYQQKPGQPPKLLIYWASTRESGVPDRFTGSGSGTDFTLTISSLQAEDVAVYYCQNDYSYPLTFGQGTKLEIK",
    "V2": "ELVMTQSPDSLAVSLGERVTMSCKSSQSLLNSGNQKNYLTWYQQKPGQPPKLLIYWASTRESGVPDRFTGSGSGTDFTLTISSVQAEDVAVYYCQNDYSYPLTFGQGTKLEIK",
    "V3": "ELVMTQSPSSLTVTAGEKVTMSCKSSQSLLNSGNQKNYLTWYQQKPGQPPKLLIYWASTRESGVPDRFTGSGSGTDFTLTISSVQAEDLAVYYCQNDYSYPLTFGQGTKLEIK",
    "Vmin": "ELVMTQSPDSLAVSLGERATISCKSSQSLLNSGNQKNYLTWYQQKPGQPPKLLIYWASTRESGVPDRFTGSGSGTDFTLTISSLQAEDVAVYYCQNDYSYPLTFGQGTKLEIK",
}

OUTPUT_DIR = "/home/jiemiaoxing/work/opencode_task/humanization/outputs/amg110_rerun/step3/step3/cdr_homology_input"

def create_paired_fasta():
    """Create paired VH/VL FASTA files for all combinations."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    # Create a single FASTA with all pairs
    fasta_path = os.path.join(OUTPUT_DIR, "all_pairs.fasta")
    
    with open(fasta_path, 'w') as f:
        for h_name, h_seq in H_VARIANTS.items():
            for l_name, l_seq in L_VARIANTS.items():
                pair_name = f"H{h_name}_L{l_name}"
                f.write(f">{pair_name}_Heavy\n{h_seq}\n")
                f.write(f">{pair_name}_Light\n{l_seq}\n")
    
    print(f"Created paired FASTA: {fasta_path}")
    return fasta_path

if __name__ == "__main__":
    create_paired_fasta()
